apiVersion: 1

datasources:
  - name: Capteurs Ynov
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true

    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
      timeInterval: 10s

    secureJsonData:
      token: ${INFLUX_TOKEN}
