services:
  influxdb:
    image: influxdb:latest
    ports:
      - "80:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      INFLUXDB_DB: ynov-iot
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: hanse-mance-mans
      DOCKER_INFLUXDB_INIT_BUCKET: my_bucket
volumes:
  influxdb_data:
