name: ynov-iot-raspberry
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      INFLUXDB_DB: ynov-iot
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: hanse-mance-mans
      DOCKER_INFLUXDB_INIT_BUCKET: my_bucket

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" # Port MQTT
      - "9001:9001" # WebSockets (si besoin)
    volumes:
      - ./mosquitto-config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    environment:
      - TZ=Europe/Paris

  python:
    build: ./python
    depends_on:
      - influxdb
      - mosquitto

  backend:
    build: ./backend
    depends_on:
      - python
    ports:
      - "8080:8080"

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:ro
      - ./web/configs:/etc/nginx/conf.d:ro
    depends_on:
      - backend

volumes:
  influxdb_data:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
