name: ${PROJECT_NAME}-raspberry
services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: ${PROJECT_NAME}
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    volumes:
      - influxdb-data:/var/lib/influxdb2

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
    environment:
      - TZ=Europe/Paris

  backend:
    build: ./backend
    depends_on:
      - mosquitto
      - influxdb
    ports:
      - 8080:8080 # For Websocket
      - 3001:3000 # For Grafana dashboard ids
    env_file:
      - .env

  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - backend

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=true # For iframe
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    env_file:
      - .env
    depends_on:
      - influxdb

  esp32-emulator:
    build: ./esp32-emulator
    profiles:
      - emulation
    depends_on:
      - mosquitto

volumes:
  influxdb-data:
  grafana-data:
